// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: NBN_dashboard

#ifndef _NBN_DASHBOARD_UI_H
#define _NBN_DASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1425725674);    // assets/image-removebg-preview (2).png
LV_IMG_DECLARE(ui_img_bolt_png);    // assets/bolt.png
LV_IMG_DECLARE(ui_img_624713029);    // assets/image-removebg-preview (1).png
LV_IMG_DECLARE(ui_img_medium_png);    // assets/medium.png
LV_IMG_DECLARE(ui_img_long_png);    // assets/long.png



LV_FONT_DECLARE(ui_font_dubi);
LV_FONT_DECLARE(ui_font_dubi2);
LV_FONT_DECLARE(ui_font_dubi3);
LV_FONT_DECLARE(ui_font_FontLUX);
LV_FONT_DECLARE(ui_font_cinzel16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
